moalemyarapi/urls.py
from django.contrib import admin
from django.contrib.messages import api
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import JsonResponse
from django.middleware.csrf import get_token


urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('api-auth/', include('rest_framework.urls')),  # for using multiuser in api and change users
                  path("api/", include("school.urls")),
                  path('', include("schoolview.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView



router = routers.DefaultRouter()

router.register(r'questions', views.QuestionViewSet)
router.register(r'subquestions', views.SubquestionViewSet)
router.register(r'courses', views.CourseViewSet)
router.register(r'books', views.BookViewSet)
router.register(r'seasons', views.SeasonViewSet)
router.register(r'lessons', views.LessonViewSet)
router.register(r'subjects', views.SubjectViewSet)
router.register(r'socialedit', views.SocialDesignerEditViewSet)


app_name = "school"
urlpatterns = [
    path("signup/", views.SignupAPIView.as_view(), name="signup"),
    path("logout/", views.LogoutAPIView.as_view(), name="logout"),
    path('api_token_auth/', views.CustomAuthToken.as_view(), name='api_token_auth'),

    path('filter_exam/', views.get_exam_filter, name='filter_exam'),
    path('exam/', views.get_exam, name='get_exam'),
    path('leitner/', views.LeitnerAPIView.as_view(), name='leitner'),
    path('leitnerquestion/', views.LeitnerQuestionViewSet.as_view(), name='leitnerquestion'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('followup/', views.FollowQuestionDesignerView.as_view(), name='followup'),

    # index
    path('index/', views.IndexAPIView.as_view(), name='api-index'),
    # question designer detail in index
    path('question_designer/<int:id>/', views.QuestionDesignerDetailAPIView.as_view(), name='question-designer-detail'),

    path('social/', views.SocialDesignerAPIView.as_view(), name='social-question-designer-detail'),
    path('social/<int:id>/', views.SocialDesignerRetrieveAPIView.as_view(), name='social-question-designer-retrieve'),

    # API schema views
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('schema/swagger/', SpectacularSwaggerView.as_view(url_name='school:schema'), name='swagger-ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name='school:schema'), name='redoc'),

    path('', include(router.urls)),


]

schoolview/urls.py
from django.urls import path
from schoolview import views
from django.contrib.auth import views as auth_views
app_name = 'schoolview'

urlpatterns = [
    # registrations
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logged_out, name='logout'),
    path('register/', views.register, name='register'),
    # 
    path('', views.index, name='index'),
    path('exam/', views.exam, name='exam'),
    path('worksheet/', views.make_worksheet, name='worksheet'),
    path('save_worksheet/', views.save_worksheet, name='save_worksheet'),
    path('leitner/', views.LeitnerView.as_view(), name='leitner'),
    path('student_profile/<int:user_id>/', views.student_profile, name='student_profile'),
    path('designer_profile/<int:user_id>/', views.designer_profile, name='designer_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('student_profile/<int:user_id>/questions/', views.questions, name='questions'),
    path('profile/subquestion_list/', views.subquestion_create_view, name='subquestion_list'),
    path('profile/right-answer/create/<int:subquestion_id>/', views.right_answer_create_view, name='right_answer_create'),
    path('profile/wrong-answer/create/<int:subquestion_id>/', views.wrong_answer_create_view, name='wrong_answer_create'),
    path('designer_profile/create-full-hierarchy/', views.create_full_hierarchy_view, name='create_full_hierarchy'),
    path('designer_profile/create_question/', views.create_question, name='create_question'),
    path('designer_profile/edit_question/<int:question_id>/', views.edit_question, name='edit_question'),
    path('designer_profile/delete_question/<int:question_id>/', views.delete_question, name='delete_question'),
    path('designer_profile/<int:designer_id>/designer-subquestions/', views.designer_subquestions, name='designer_subquestions'),
    path('edit-subquestion/<int:subquestion_id>/', views.edit_subquestion, name='edit_subquestion'),
    path('designer_profile/<int:user_id>/designer-questions/', views.designer_questions, name='designer_questions'),
    path('designer_profile/<int:designer_id>/student/<int:student_id>/', views.student_status_view, name='student_status'),
    path('designer_profile/<int:designer_id>/designer-questions/<int:subquestion_id>/delete', views.delete_subquestion, name='delete_subquestion'),
    path('student_profile/<int:student_id>/leitner_questions', views.student_leitner_questions, name='student_leitner_questions'),
    path('student_profile/<int:student_id>/leitner_questions/<int:subquestion_id>/add/', views.add_to_leitner, name='add_to_leitner'),
    path('student_profile/<int:student_id>/leitner_questions/<int:subquestion_id>/remove/', views.remove_from_leitner, name='remove_from_leitner'),
    path('subquestion_view/<int:subquestion_id>/', views.subquestion_view, name='subquestion_view'),
    path('ajax/hierarchy-fetch/', views.ajax_hierarchy_fetch, name='ajax_hierarchy_fetch'),


    path('ajax/get-books/', views.get_books, name='get_books'),
    path('ajax/get-seasons/', views.get_seasons, name='get_seasons'),
    path('ajax/get-lessons/', views.get_lessons, name='get_lessons'),
    path('ajax/get-subjects/', views.get_subjects, name='get_subjects'),

]

schoolview/models.py
from django.db import models

# Create your models here.

school/views.py
from rest_framework import status, generics, mixins
from rest_framework.exceptions import PermissionDenied
from rest_framework.response import Response
from rest_framework.request import Request
from rest_framework.views import APIView
from rest_framework import viewsets, generics
from rest_framework.permissions import IsAuthenticated, AllowAny
from .serializer import *
from .permissions import *
from django.shortcuts import get_object_or_404
from .models import *
from rest_framework.decorators import api_view, permission_classes
from django.http import JsonResponse
from django.middleware.csrf import get_token
from .tasks import process_exam_answers
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from account.models import CustomUser
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from rest_framework.decorators import action
from django.db.models import Sum, Avg, Count, Q, F, ExpressionWrapper, IntegerField
from rest_framework.pagination import PageNumberPagination


class CustomAuthToken(ObtainAuthToken):
    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data,
                                           context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'user_id': user.pk,
            'code_meli': user.code_meli,
            'username': user.username,

        })


class SignupAPIView(APIView):
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        serializer = SignupSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LogoutAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            request.user.auth_token.delete()
            return Response({"message": "Successfully logged out."}, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_400_BAD_REQUEST)


class CheckAuthView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        return JsonResponse({"user": {"username": request.user.username}})


class CSRFTokenView(APIView):
    def get(self, request):
        return JsonResponse({"csrfToken": get_token(request)})


class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionsSerializer
    permissions_classes = (IsQuestionDesigner,)

    @action(detail=True, methods=['delete'], url_path='delete_title')
    def delete_title(self, request, pk=None):
        question = self.get_object()
        question.title = ''
        question.save()
        return Response({'message': 'عنوان حذف شد'}, status=status.HTTP_204_NO_CONTENT)

    @action(detail=True, methods=['delete'], url_path='delete_audio_file')
    def delete_audio_file(self, request, pk=None):
        question = self.get_object()
        question.audio_file.delete(save=False)
        question.audio_file = None
        question.save()
        return Response({'message': 'فایل صوتی حذف شد'}, status=status.HTTP_204_NO_CONTENT)

    @action(detail=True, methods=['delete'], url_path='delete_image')
    def delete_image(self, request, pk=None):
        question = self.get_object()
        question.image.delete(save=False)
        question.image = None
        question.save()
        return Response({'message': 'تصویر حذف شد'}, status=status.HTTP_204_NO_CONTENT)


class SubquestionViewSet(viewsets.ModelViewSet):
    queryset = Subquestion.objects.all()
    serializer_class = SubquestionSerializer
    permission_classes = [IsQuestionDesigner]
    parser_classes = [MultiPartParser, FormParser, JSONParser]

    def get_queryset(self):
        custom_user = self.request.user
        question_designer = Question_designer.objects.filter(designer=custom_user).first()
        return Subquestion.objects.filter(question_designer=question_designer)


class CourseViewSet(viewsets.ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class SeasonViewSet(viewsets.ModelViewSet):
    queryset = Season.objects.all()
    serializer_class = SeasonSerializer


class LessonViewSet(viewsets.ModelViewSet):
    queryset = Lesson.objects.all()
    serializer_class = LessonSerializer


class SubjectViewSet(viewsets.ModelViewSet):
    queryset = Subject.objects.all()
    serializer_class = SubjectSerializer


@permission_classes([IsAuthenticated])
@api_view(['GET', 'POST'])
def get_exam_filter(request: Request):
    if request.method == 'GET':
        return Response({
            'courses': CourseSerializer(Course.objects.all(), many=True).data,
            'books': BookSerializer(Book.objects.all(), many=True).data,
            'seasons': SeasonSerializer(Season.objects.all(), many=True).data,
            'lessons': LessonSerializer(Lesson.objects.all(), many=True).data,
            'subjects': SubjectSerializer(Subject.objects.all(), many=True).data,
        }, status=status.HTTP_200_OK)

    elif request.method == 'POST':
        course_ids = request.data.get('course_ids', [])
        book_ids = request.data.get('book_ids', [])
        season_ids = request.data.get('season_ids', [])
        lesson_ids = request.data.get('lesson_ids', [])
        subject_ids = request.data.get('subject_ids', [])

        courses = Course.objects.filter(id__in=course_ids)
        books = Book.objects.filter(id__in=book_ids)
        seasons = Season.objects.filter(id__in=season_ids)
        lessons = Lesson.objects.filter(id__in=lesson_ids)
        subjects = Subject.objects.filter(id__in=subject_ids)

        if len(courses) != len(course_ids):
            return Response({'error': 'Some courses not found'}, status=status.HTTP_400_BAD_REQUEST)
        if len(books) != len(book_ids):
            return Response({'error': 'Some books not found'}, status=status.HTTP_400_BAD_REQUEST)
        if len(seasons) != len(season_ids):
            return Response({'error': 'Some seasons not found'}, status=status.HTTP_400_BAD_REQUEST)
        if len(lessons) != len(lesson_ids):
            return Response({'error': 'Some lessons not found'}, status=status.HTTP_400_BAD_REQUEST)
        if len(subjects) != len(subject_ids):
            return Response({'error': 'Some subjects not found'}, status=status.HTTP_400_BAD_REQUEST)

        request._request.session['course_ids'] = course_ids
        request._request.session['book_ids'] = book_ids
        request._request.session['season_ids'] = season_ids
        request._request.session['lesson_ids'] = lesson_ids
        request._request.session['subject_ids'] = subject_ids

        return Response({
            'message': 'your categories selected'
        }, status=200)


@api_view(['GET', 'POST'])
@permission_classes([IsAuthenticated])
def get_exam(request: Request):
    course_ids = request.session.get('course_ids', [])
    book_ids = request.session.get('book_ids', [])
    season_ids = request.session.get('season_ids', [])
    lesson_ids = request.session.get('lesson_ids', [])
    subject_ids = request.session.get('subject_ids', [])

    student = Student.objects.filter(student=request.user).first()
    if request.method == "GET":

        subquestions = Subquestion.objects.filter(
            Q(course__in=course_ids) |
            Q(book__in=book_ids) |
            Q(season__in=season_ids) |
            Q(lesson__in=lesson_ids) |
            Q(subject__in=subject_ids)
        ).annotate(
            zero_sum=Sum('practice__zero'),
            nf_sum=Sum('practice__nf'),
            nt_sum=Sum('practice__nt'),
        ).annotate(
            total_calculation=ExpressionWrapper(
                ((F('zero_sum') * 2 - 1) * (F('nf_sum') + 1)) / (F('nt_sum') + 1),
                output_field=IntegerField()
            )
        ).order_by('-total_calculation')

        subquestions_serializer = ExamSubquestionSerializer(subquestions, many=True)
        subquestions_data = subquestions_serializer.data

        right_answers = [
            {
                'subquestion_id': subquestion.id,
                'right_answer_id': correct_answer.id
            }
            for subquestion in subquestions
            for correct_answer in Right_answer.objects.filter(subquestion_id=subquestion.id, type__isnull=False)
        ]
        request.session['subquestions_serializer'] = subquestions_data
        request.session['right_answers'] = right_answers
        return Response(subquestions_data, status=status.HTTP_200_OK)

    elif request.method == "POST":
        """
        {
         "answers":{
            "9":10,
            "11":12
        }}
        """

        user_answers = request.data.get('answers', {})
        right_answers = request.session.get('right_answers', [])
        subquestions_serializer = request.session.get('subquestions_serializer', {})

        if not user_answers:
            return Response({'error': 'no answers'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            task = process_exam_answers.delay(
                request.user.id,
                user_answers,
                right_answers,
                subquestions_serializer

schoolview/templates/school/designer_profile.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}ثبت صورت سوال{% endblock %}
{% block content %}
    <div class="designer-dashboard">
        <div class="profile-header">
            <a href="{% url 'schoolview:edit_profile' %}">
            {% if designer.designer.profile %}
                <img src="{{ designer.designer.profile.url }}" alt="photo" class="rounded-image">
            {% endif %}
            <h1>Hello {{ user.username }}</h1>
            </a>
        </div>


        <!-- Main Links -->
        <div class="main-links">
            <a href="{% url 'schoolview:create_full_hierarchy' %}" class="main-link">ساخت سلسله مراتب جدید</a>
            <br>
            <a href="{% url 'schoolview:designer_questions' user.id %}" class="main-link">صورت سوالات</a>
            <br>
            <a href="{% url 'schoolview:designer_subquestions' request.user.id %}" class="main-link">سوالات طرح شده</a>
            <br>
        </div>

        <!-- Students Section -->
        <h3 class="students-title">دانش‌آموزان</h3>
        <div class="student-links">
            {% for student in students %}
                <a href="{% url 'schoolview:student_status' user.id student.id %}" class="student-link">{{ student }}</a>
            {% endfor %}
        </div>
    </div>

{% endblock %}

schoolview/templates/school/designer_questions.html
{% extends 'parent/base.html' %}
{% block title %} صورت سوال ها{% endblock %}

{% block content %}
    <div class="question-container">
        <!-- Create New Question Button -->
        <a href="{% url 'schoolview:create_question' %}" class="create-button">ساخت صورت سوال</a>

        <!-- Question List -->
        {% for question in questions %}
            <div class="question-box">
                <p class="question-text">{{ question.title }}</p>

                <!-- Display Question Image -->
                {% if question.image %}
                    <div class="question-media">
                        <img src="{{ question.image.url }}" alt="تصویر سوال" class="question-image">
                    </div>
                {% endif %}

                <!-- Display Question File -->
                {% if question.file %}
                    <div class="question-media">
                        <a href="{{ question.file.url }}" class="file-link" target="_blank">دانلود فایل</a>
                    </div>
                {% endif %}

                <!-- Action Buttons -->
                <div class="action-buttons">
                    <a href="{% url 'schoolview:edit_question' question.id %}" class="edit-button">ویرایش</a>
                    <a href="{% url 'schoolview:delete_question' question.id %}" class="delete-button" onclick="return confirm('آیا مطمئن هستید که می‌خواهید این سوال را حذف کنید؟')">حذف</a></div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

schoolview/templates/school/designer_subquestions.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}سوال ها{% endblock %}
{% block content %}
    <div class="subquestion-container">
        <!-- Create New Subquestion Button -->
        <a href="{% url 'schoolview:subquestion_list' %}" class="create-button">ساخت سوال جدید</a>

        <!-- Subquestion List -->
        {% for subquestion in subquestions %}
            <div class="question-box">
                <h3 class="question-title">سوال:</h3>
                <p class="question-text">{{ subquestion.text }}</p>

                <!-- Subquestion Image -->
                {% if subquestion.image %}
                    <img src="{{ subquestion.image.url }}" alt="تصویر سوال" class="question-image">
                {% endif %}

                <!-- Correct Answers -->
                <h4 class="answer-title">جواب‌های درست:</h4>
                {% for answer in subquestion.right_answer.all %}
                    <div class="answer-item">
                        <p class="answer-text">{{ answer.title }}</p>
                        {% if answer.image %}
                            <img src="{{ answer.image.url }}" alt="تصویر جواب درست" class="answer-image">
                        {% endif %}
                        {% if answer.audio_file %}
                            <audio controls class="answer-audio">
                                <source src="{{ answer.audio_file.url }}" type="audio/mpeg">
                                مرورگر شما از پخش صوتی پشتیبانی نمی‌کند.
                            </audio>
                        {% endif %}
                    </div>
                {% empty %}
                    <p class="no-answer">جواب درست ثبت نشده است.</p>
                {% endfor %}

                <!-- Wrong Answers -->
                <h4 class="answer-title">جواب‌های غلط:</h4>
                {% for answer in subquestion.wrong_answer.all %}
                    <div class="answer-item">
                        <p class="answer-text">{{ answer.title }}</p>
                        {% if answer.image %}
                            <img src="{{ answer.image.url }}" alt="تصویر جواب غلط" class="answer-image">
                        {% endif %}
                        {% if answer.audio_file %}
                            <audio controls class="answer-audio">
                                <source src="{{ answer.audio_file.url }}" type="audio/mpeg">
                                مرورگر شما از پخش صوتی پشتیبانی نمی‌کند.
                            </audio>
                        {% endif %}
                    </div>
                {% empty %}
                    <p class="no-answer">جواب غلط ثبت نشده است.</p>
                {% endfor %}

                <!-- Edit and Delete Buttons -->
                <div class="action-buttons">
                    <a href="{% url 'schoolview:edit_subquestion' subquestion.id %}" class="edit-button">ویرایش</a>
                    <a href="{% url 'schoolview:delete_subquestion' user.id subquestion.id %}" class="delete-button"  onclick="return confirm('آیا مطمئن هستید که می‌خواهید این سوال را حذف کنید؟')">حذف</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

schoolview/templates/school/profile.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="profile-container">
    <div class="profile-header">
        {% if student.student.profile %}
            <img src="{{ student.student.profile.url }}" alt="photo" class="rounded-image">
        {% endif %}
        <h1>Hello {{ user.username }}</h1>
    </div>

    <div class="leitner-section">
        {% if leitner.datel != current_date %}
                <div class="exam-section">
                    <a href="{% url 'schoolview:leitner' %}" class="leitner-button">Do Leitner</a>

                 </div>
        {% else %}
            <p class="leitner-message">You did your Leitner for today!</p>
        {% endif %}
    </div>

    <div class="exam-section">
        <a href="{% url 'schoolview:exam' %}" class="exam-button">exam</a>

    </div>

    <h3>تمرین های روز</h3>
    <table>
        <thead>
            <tr>
                <th>تاریخ</th>
                <th>زمان کل</th>
                <th>زمان سپری شده</th>
            </tr>
        </thead>
        <tbody>
            {% for worksheet in worksheets %}
                <tr>
                    <td>{{ worksheet.date }}</td>
                    <td>{{ worksheet.total_time }}</td>
                    <td> {{ worksheet.time_spent }} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


    <div class="logout-section">
        <a href="{% url 'schoolview:edit_profile' %}" class="logout-button">edit profile</a>

        <a href="{% url 'schoolview:logout' %}" class="logout-button">Logout</a>
    </div>
</div>
{% endblock %}

schoolview/templates/school/questions.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}

{% if request.user.is_student %}


      <table>
        <thead>
            <tr>
                <th>سوال</th>
                <th>اخرین تاریخ تمرین</th>
                <th>تعدا دفعات غلط</th>
                <th>تعداد دفعات درست</th>
                <th>تعداد اشتباهات متوالی </th>
            </tr>
        </thead>
        <tbody>
            {% for question in questions %}
                <tr>
                    <td>
                        {% for subquestion in question.subquestion.all %}
                            <a href="{% url 'schoolview:subquestion_view' subquestion.id %}">{{ subquestion.text }}</a>
                        {% endfor %}
                    </td>
                    <td>{{ question.date }}</td>
                    <td> {{ question.nf }} </td>
                    <td>{{ question.nt }}</td>
                    <td>{{ question.zero }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}

    hi

{% endif %}
{% endblock %}

schoolview/templates/school/student_leitner_questions.html
{% extends 'parent/base.html' %}
{% load teacher_tags %}
{% load static %}
{% block title %}سوالات لایتنر دانش اموز{% endblock %}
{% block content %}
   <table border="1">
        <thead>
            <tr>
                <th>متن سوال</th>
                <th>وضعیت</th>
                <th>اقدام</th>
            </tr>
        </thead>
        <tbody>
            {% for question in question_status %}
                <tr>
                    <td><a href="{% url 'schoolview:subquestion_view' question.id %}">{{ question.text }}</a></td>
                    {% if question.status %}
                        <td>موجود در لایتنر</td>
                        <td><a href="{% url 'schoolview:remove_from_leitner' student.id question.id %}">حذف از لایتنر</a></td>
                    {% else %}
                        <td>موجود نیست در لایتنر</td>
                        <td><a href="{% url 'schoolview:add_to_leitner' student.id question.id %}">اضافه کردن به لایتنر</a></td>

                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

schoolview/templates/school/student_profile.html
{% extends 'parent/base.html' %}
{% load teacher_tags %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
<div class="profile-container">
    <div class="profile-header">
        <a href="{% url 'schoolview:edit_profile' %}">
            {% if student.student.profile %}
                <img src="{{ student.student.profile.url }}" alt="photo" class="rounded-image">
            {% endif %}
            <h1>Hello {{ user.username }}</h1>
        </a>
    </div>

    <div class="leitner-section">
    {% if leitner_question %}
        {% if leitner.datel != current_date or leitner.last_step != 1 %}
                <div class="exam-section">
                    <a href="{% url 'schoolview:leitner' %}" class="leitner-button">Do Leitner</a>
                </div>
        {% else %}
            <p class="leitner-message">You did your Leitner for today!</p>
        {% endif %}
    {% else %}
        <p class="leitner-message">you have not added any question in leitner questions</p>
    {% endif %}
    </div>

    <div class="exam-section">
        <a href="{% url 'schoolview:exam' %}" class="exam-button">exam</a>
        <a href="{% url 'schoolview:questions' user.id %}" class="exam-button">وضعیت من در سوال ها</a>
        <a href="{% url 'schoolview:student_leitner_questions' student.id %}" class="exam-button">سوالات لایتنر</a>

    </div>

    <h3>تمرین های روز</h3>
    <table>
        <thead>
            <tr>
                <th>تاریخ</th>
                <th>زمان کل</th>
                <th>زمان سپری شده</th>
            </tr>
        </thead>
        <tbody>
            {% for worksheet in worksheets %}
                <tr>
                    <td>{{ worksheet.date }}</td>
                    <td>{{ worksheet.total_time }}</td>
                    <td> {{ worksheet.time_spent }} </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>


    <div class="logout-section">
        <a href="{% url 'schoolview:logout' %}" class="logout-button">Logout</a>
    </div>
</div>
{% endblock %}

schoolview/templates/school/student_status.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %} وضعیت دانش آموز {% endblock %}
{% block content %}
<div class="student-status-container">
    <h2 class="student-status-title">وضعیت دانش‌آموز: {{ student }}</h2>

    <!-- Leitner Section -->
    <h3 class="student-status-section-title">لایتنر</h3>
    <a href="{% url 'schoolview:student_leitner_questions' student.id %}">سوالات لایتنر</a>
    <ul class="student-status-list">
        {% for item in student.leitner.all %}
            <li class="student-status-item"> آخرین چک: {{ item.datel }} </li>
        {% empty %}
            <li class="student-status-empty">هیچ موردی در لایتنر وجود ندارد.</li>
        {% endfor %}
    </ul>

    <!-- Subquestions Section -->
    <h3 class="student-status-section-title">زیرسوال‌ها</h3>
    <ul class="student-status-list">
        {% for subquestion in subquestions %}
            <li class="student-status-item">
                <strong class="student-status-strong">سؤال:</strong> {{ subquestion }}
                <ul class="student-status-nested-list">
                    {% for practice in practices %}
                        {% if subquestion in practice.subquestion.all %}
                            <li class="student-status-nested-item">
                                <strong class="student-status-strong">تعداد غلط های پشت سر هم:</strong> {{ practice.zero }}
                            </li>
                            <li class="student-status-nested-item">
                                <strong class="student-status-strong">تعداد نادرست:</strong> {{ practice.nf }}
                            </li>
                            <li class="student-status-nested-item">
                                <strong class="student-status-strong">تعداد درست:</strong> {{ practice.nt }}
                            </li>
                            <li class="student-status-nested-item">
                                <strong class="student-status-strong">تاریخ:</strong> {{ practice.date }}
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </li>
        {% empty %}
            <li class="student-status-empty">هیچ سوالی برای تمرین ثبت نشده است.</li>
        {% endfor %}
    </ul>

    <!-- Worksheets Section -->
    <h3 class="student-status-section-title">کارنامه ها</h3>
    {% if worksheets %}
        <ul class="student-status-list">
            {% for worksheet in worksheets %}
                <li class="student-status-worksheet">
                    <strong class="student-status-strong">تاریخ کارنامه:</strong> {{ worksheet.date }}
                    <ul class="student-status-nested-list">
                        <li class="student-status-nested-item">
                            <strong class="student-status-strong">زمان کل:</strong> {{ worksheet.total_time }}
                        </li>
                        <li class="student-status-nested-item">
                            <strong class="student-status-strong">زمان صرف شده:</strong> {{ worksheet.time_spent }}
                        </li>
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="student-status-empty">هیچ کارنامه‌ای ثبت نشده است.</p>
    {% endif %}
</div>
{% endblock %}